/// The `main` function is the entry point of your application.
///
/// It gets called when you invoke `cargo run --bin jira-wip` and
/// its executed when a user runs the binary you generated by compiling your project
/// (`cargo build` -> `/target/debug/jira-wip` / `cargo build --release` -> `/target/release/jira-wip`)
///
/// Over the course of this workshop we will modify this entry point to build a fully fledged
/// command line application.
///
/// Brace yourself!
fn main() {
    println!(
        "Welcome to the Rust LDN Code Dojo!\nGet Ready to build your own Jira with Rust, IronJira!"
    );
}
